### ISSUE TITLE
Swift 3 Support

### ISSUE THREAD

**Issue by cloke** [demetrio812/EurekaCreditCard#3]
There are several issues to get this working under Swift 3. The converter fixes about 130 of them, but then 14 or so remain.

**Comment by cloke** [comment]
Submitted PR #4 to support swift 3.

**Comment by demetrio812** [comment]
Hello! Thanks for the PR, I've used it but I had to do some other changes (did you use a non-final version of XCode to convert it?).

However everything has been committed to another branch, I'm waiting for the release of Eureka for Swift 3 in order to be able to create a new release.

Thanks,
Dem
